name: Deploying application to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./SimpleApplication
        run: npm install
      - name: Build
        working-directory: ./SimpleApplication
        run: npm run build
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: BfAwybr0D08WzG85uTRQo8RC
          vercel-org-id: 2Wd4hd2lBRJSdTAowUIVbH83
          vercel-project-id: prj_538N5WGH2qzgT3VZULohurbibWVk
          github-token: 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
          prod: true
